# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_auto_20161215_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFiling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_name', models.CharField(blank=True, max_length=250, null=True)),
                ('ticker', models.CharField(blank=True, max_length=250, null=True)),
                ('position', models.CharField(blank=True, max_length=250, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
            ],
            options={
                'verbose_name_plural': 'Company Filings',
            },
        ),
        migrations.CreateModel(
            name='SecurityAcquired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_security', models.CharField(blank=True, max_length=250, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('deemed_execution_date', models.DateField(blank=True, null=True)),
                ('transaction_code', models.CharField(blank=True, max_length=250, null=True)),
                ('transaction_code_v', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('amount_a_or_d', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('amount_owned_after_transaction', models.IntegerField(blank=True, null=True)),
                ('ownership_form', models.CharField(blank=True, max_length=250, null=True)),
                ('nature_of_indirect', models.CharField(blank=True, max_length=250, null=True)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_filings.CompanyFiling')),
            ],
            options={
                'verbose_name_plural': 'Securities Acquired',
            },
        ),
    ]
