# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_filings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyfiling',
            old_name='position',
            new_name='officer_title',
        ),
        migrations.RenameField(
            model_name='securityacquired',
            old_name='amount_a_or_d',
            new_name='direct_or_indirect_ownership',
        ),
        migrations.RenameField(
            model_name='securityacquired',
            old_name='nature_of_indirect',
            new_name='security_title',
        ),
        migrations.RenameField(
            model_name='securityacquired',
            old_name='amount',
            new_name='shares_owned_following_transaction',
        ),
        migrations.RenameField(
            model_name='securityacquired',
            old_name='ownership_form',
            new_name='transaction_acquired_disposed_code',
        ),
        migrations.RenameField(
            model_name='securityacquired',
            old_name='title_of_security',
            new_name='transaction_form_type',
        ),
        migrations.RenameField(
            model_name='securityacquired',
            old_name='price',
            new_name='transaction_price_per_share',
        ),
        migrations.RenameField(
            model_name='securityacquired',
            old_name='amount_owned_after_transaction',
            new_name='transaction_shares',
        ),
        migrations.AddField(
            model_name='companyfiling',
            name='is_director',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='companyfiling',
            name='is_officer',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='companyfiling',
            name='is_ten_percent_owner',
            field=models.NullBooleanField(),
        ),
    ]
