# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_filings', '0002_auto_20161215_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyfiling',
            old_name='filing_name',
            new_name='report_owner_name',
        ),
    ]
