# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_filings', '0004_remove_securityacquired_deemed_execution_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityacquired',
            name='transaction_code_v',
        ),
    ]
