# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_filings', '0006_auto_20161215_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityacquired',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
