# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ticker',
            field=models.CharField(max_length=10, unique=True, verbose_name='Ticker'),
        ),
    ]
