# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161215_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompanies',
            name='company_list',
        ),
        migrations.AddField(
            model_name='usercompanies',
            name='tracked_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Company'),
        ),
    ]
