# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-19 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20161217_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercompanies',
            options={'ordering': ['tracked_company__name'], 'verbose_name_plural': 'User Tracked Companies'},
        ),
    ]
