# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-19 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20161218_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompanies',
            name='tracked_company',
        ),
        migrations.AddField(
            model_name='usercompanies',
            name='tracked_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Company'),
            preserve_default=False,
        ),
    ]
