# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20161219_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompanies',
            name='tracked_company',
        ),
        migrations.RemoveField(
            model_name='usercompanies',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserCompanies',
        ),
    ]
