# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 04:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_auto_20161219_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tracked_company__name'],
                'verbose_name_plural': 'User Tracked Companies',
            },
        ),
    ]
