# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_usercompanies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='usercompanies',
            name='tracked_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Company'),
        ),
    ]
