# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 04:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20161219_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompanies',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
