# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20161219_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompanies',
            name='tracked_company',
        ),
        migrations.AddField(
            model_name='usercompanies',
            name='tracked_company',
            field=models.ManyToManyField(null=True, to='home.Company'),
        ),
    ]
