# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-26 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_company_market_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Market Cap'),
        ),
    ]
