# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-26 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_company_beta'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='beta',
            field=models.FloatField(blank=True, null=True, verbose_name='Beta'),
        ),
    ]
