# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-26 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_company_beta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='EPS',
        ),
        migrations.RemoveField(
            model_name='company',
            name='EV_To_EBITDA',
        ),
        migrations.RemoveField(
            model_name='company',
            name='EV_To_Rev',
        ),
        migrations.RemoveField(
            model_name='company',
            name='PE_ratio',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Price_To_Book',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Price_To_Sales',
        ),
        migrations.RemoveField(
            model_name='company',
            name='beta',
        ),
        migrations.RemoveField(
            model_name='company',
            name='employee_count',
        ),
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sector',
        ),
    ]
